### ISSUE TITLE
Update demos to Iceberg 0.13.0 / Nessie 0.18.0

### ISSUE THREAD

**Issue by nastra** [projectnessie/nessie-demos#260]

**Comment by ajantha-bhat** [comment]
@nastra : Should it be nessie 0.19.0 ? Because 0.18.0 has old nessie spark extensions ?

**Comment by nastra** [comment]
It needs to be Nessie 0.18.0 I believe (the version that is being used in Iceberg 0.13.0), but worth trying if we can use Nessie 0.19.0

**Comment by ajantha-bhat** [comment]
> It needs to be Nessie 0.18.0 I believe (the version that is being used in Iceberg 0.13.0), but worth trying if we can use Nessie 0.19.0

but version that is being used by iceberg is not having the latest nessie spark extensions due to our circular dependency. So, I think it cannot be 0.18.0 as demos need nessie spark extensions.

**Comment by XN137** [comment]
maybe the flink demo could be updated to Flink 1.14.0 along the way due to https://github.com/apache/iceberg/commit/2d4b0ddc76fd47aa27ca4972d4f3a6f256921c58

**Comment by XN137** [comment]
it was noticed that the demo links to https://projectnessie.org/tools/spark/ but it should be https://projectnessie.org/tools/iceberg/spark/

so we should also update that

**Comment by ajantha-bhat** [comment]
note to @XN137 : You can try with nessie 0.18.0, but I think nessie spark session extensions were upgraded in 0.19.0 so it will not work. 

There is a circular dependency,
Nessie makes a release (0.18.0)-> Iceberg makes a release with that nessie (0.13.1) -> nessie updates its spark extensions with that iceberg version (0.19.0)

If it works on 0.18.0, let me know also. I am also curious to see whether my understanding is right or not.
