### ISSUE TITLE
Nessie + Delta Demo

### ISSUE THREAD

**Issue by snazy** [projectnessie/nessie-demos#59]
Demo related code is there.

TODOs:
* Mention in README.md
* Finish configs + move out of `in-development`
* Add to projectnessie.org site

Depends on https://github.com/projectnessie/nessie/pull/1249

**Comment by nastra** [comment]
Added links to the Deltalake demo in https://github.com/projectnessie/nessie/pull/1408 and in https://github.com/projectnessie/nessie-demos/pull/82
